browser=chrome
url=https://www.automationexercise.com
username=aishwaryabalu996@gmail.com
password=k@2Q54wyqkPHFt
timeout=10
firstName=Aishwarya
lastName=Balu
address=abc Main Street
city=Chennai
state=Tamil Nadu
zipCode=600001 
cardName=Aish
cardNumber=4111111111111111
cvc=123
expiryMonth=12
expiryYear=2030