browser=chrome
url=https://www.automationexercise.com
username=aishwaryabalu996@gmail.com
password=k@2Q54wyqkPHFt
timeout=10
firstName=Muthu
lastName=Muthu
address=abc Main Street
city=Tirunelveli
state=Tamil Nadu
zipCode=627425
cardName=Aish
cardNumber=4111111111111111
cvc=123
expiryMonth=12
expiryYear=2030